---
title: "Project Report"
output: 
  html_notebook: 
    number_sections: yes
---

# Team members

- Ahmed Ashraf Mohamed
  - ID: 2022446758
- Abdelrhman Mohamed Abdelhady Hodid
  - ID : 2022513643
- Antonuose Gerges Nageh
  - ID : 20221903971
  
# Project Description

# Getting data set
## importing the library we are going to use
```{r}
library(dplyr)
library(ggplot2)
```
```{r Getting data, echo=TRUE}
dataPath <- readline("Enter the path to the data set : ")
grc <- as_tibble(read.csv(dataPath))
# displaying first 10 rows of our data
print(grc)
```
# Visualizing our Data
## Comparison between cash and creadit total spending using box plot
```{r}
ggplot(
  grc,
  aes(x = paymentType, y = total)
  ) +
  geom_boxplot(width = .2, 
               fill = "orange",
               outlier.color = "orange",
               outlier.size = 2)
```
## Compare each age and sum of total spending.

```{r}
grc_age <- select(grc,age,total)
grc_age <- group_by(grc_age, age)
grc_age <- summarise(grc_age,totalSpending = sum(total))
print(grc_age)
ggplot(grc_age,aes(x = age, y = totalSpending)) + geom_col()
ggplot(grc_age, aes(x= age, y = totalSpending, group =1)) + geom_boxplot(outlier.size = 2)
```

